### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by DerFetzer**
This PR adds a Dockerfile and makes some parameters configurable via environment variables.

### CODE REVIEW

**Comment by danielkucera** [comment]
Nice, thank you, can you please rebase on latest master?

**Comment by DerFetzer** [comment]
I did the rebase and added some more variables but there is an issue with image preparation at the moment. I'll keep you posted.

**Comment by DerFetzer** [comment]
I did a mistake while rebasing. Now it is working again for me.

**Comment by danielkucera** [comment]
Nice, thank you.

**Pull request merged**
